from .import patient
from .import doctor
from .import medication
from .import appointment
from .import room
from .import patient_in
from .import patient_out
from .import laboratry
from .import doctors_department
from .import product_stock
